# Generated by Django 3.0.4 on 2020-04-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Thanks for visiting my blog website', max_length=200),
        ),
    ]
